stages:
  - build
  - push
  - deliver
  - promote
  - deploy

# -----------------------------
# Build Stage
# -----------------------------
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd auth
    - docker build -t $CI_REGISTRY_USER/weatherapp-auth . --no-cache
    - cd ../UI
    - docker build -t $CI_REGISTRY_USER/weatherapp-ui .
    - cd ../weather
    - docker build -t $CI_REGISTRY_USER/weatherapp-weather .
  rules:
    - if: '$CI_COMMIT_TAG == null'

# -----------------------------
# Push Stage
# -----------------------------
push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd auth
    - docker build -t $CI_REGISTRY_USER/weatherapp-auth:$CI_COMMIT_SHA . --no-cache
    - docker push $CI_REGISTRY_USER/weatherapp-auth:$CI_COMMIT_SHA
    - cd ../UI
    - docker build -t $CI_REGISTRY_USER/weatherapp-ui:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_USER/weatherapp-ui:$CI_COMMIT_SHA
    - cd ../weather
    - docker build -t $CI_REGISTRY_USER/weatherapp-weather:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_USER/weatherapp-weather:$CI_COMMIT_SHA
  only:
    - main

# -----------------------------
# Deliver Stage
# -----------------------------
deliver:
  stage: deliver
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  before_script:
    - apk add --no-cache curl bash aws-cli
    - aws configure set region "eu-west-1"
    - mkdir -p /tmp/.kube
    - echo "$K8SCONFIG" | base64 -d > /tmp/.kube/config
    - helm repo add bitnami https://charts.bitnami.com/bitnami
  script:
    - cd weatherapp-auth
    - helm dependency build .
    - helm upgrade --install weatherapp-auth . --kubeconfig /tmp/.kube/config -n staging --set mysql.auth.rootPassword=$DB_PASSWORD --set image.tag=$CI_COMMIT_SHA --set mysql.primary.persistence.enabled=false
    - cd ../weatherapp-ui
    - helm upgrade --install weatherapp-ui . --kubeconfig /tmp/.kube/config -n staging --set image.tag=$CI_COMMIT_SHA
    - cd ../weatherapp-weather
    - helm upgrade --install weatherapp-weather . --kubeconfig /tmp/.kube/config -n staging --set apikey=$API_KEY --set image.tag=$CI_COMMIT_SHA
  only:
    - main

# -----------------------------
# Promote Stage
# -----------------------------
promote:
  stage: promote
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add git
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - export TAGGED_HASH=$(git rev-list -n 1 $CI_COMMIT_TAG)
  script:
    - echo "Promoting Docker images"
    - docker pull $CI_REGISTRY_USER/weatherapp-ui:$TAGGED_HASH
    - docker pull $CI_REGISTRY_USER/weatherapp-auth:$TAGGED_HASH
    - docker pull $CI_REGISTRY_USER/weatherapp-weather:$TAGGED_HASH
    - docker tag $CI_REGISTRY_USER/weatherapp-ui:$TAGGED_HASH $CI_REGISTRY_USER/weatherapp-ui:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_USER/weatherapp-auth:$TAGGED_HASH $CI_REGISTRY_USER/weatherapp-auth:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_USER/weatherapp-weather:$TAGGED_HASH $CI_REGISTRY_USER/weatherapp-weather:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_USER/weatherapp-ui:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_USER/weatherapp-auth:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_USER/weatherapp-weather:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG'

# -----------------------------
# Deploy Stage
# -----------------------------
deploy:
  stage: deploy
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  before_script:
    - apk add --no-cache aws-cli
    - aws configure set region "eu-west-2"
    - mkdir -p /tmp/.kube
    - echo "$K8SCONFIG" | base64 -d > /tmp/.kube/config
    - helm repo add bitnami https://charts.bitnami.com/bitnami
  script:
    - cd weatherapp-auth
    - helm dependency build .
    - helm upgrade --install weatherapp-auth . --kubeconfig /tmp/.kube/config -n staging --set mysql.auth.rootPassword=$DB_PASSWORD --set image.tag=$CI_COMMIT_TAG
    - cd ../weatherapp-ui
    - helm upgrade --install weatherapp-ui . --kubeconfig /tmp/.kube/config -n staging --set image.tag=$CI_COMMIT_TAG
    - cd ../weatherapp-weather
    - helm upgrade --install weatherapp-weather . --kubeconfig /tmp/.kube/config -n staging --set apikey=$API_KEY --set image.tag=$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual

